### ISSUE TITLE
Shared library option request

### ISSUE THREAD

**Issue by majnerp1** [Quark987/plugin.video.moments#1]
Please implement viewing/browsing photos from shared library too. Browsing personal library woks well.

**Comment by Quark987** [comment]
Hi,

That functionality should already be there. Are you sure you installed the latest release from here? https://github.com/Quark987/plugin.video.moments/releases/tag/v0.1

Then you should be able to access the shared albums by browsing to shared -> shared with me / others -> albums

Also, if you view the shared albums using a browser, can you then see the albums without any issues? Do you also get any errors or anything like that?

**Comment by majnerp1** [comment]
I had in mind a shared library between Synology users, located in the /photos directory (also used by Photo Station). On the Moments website, there is a switch option under the Moments logo.

**Comment by Quark987** [comment]
Ok, I understand what you mean. It shouldn't be too hard to add this, but as I do not use this feature I'll need your assistance to debug it. I'll let you know when it's ready.

**Comment by Quark987** [comment]
Shared library support is now added, you can download the latest version [here](https://github.com/Quark987/plugin.video.moments/archive/master.zip)

It's only going to show up if you have albums in this library. Please let me know if there are any issues.
When installing this new version, don't forget to reboot before running the first time.

**Comment by majnerp1** [comment]
Hello, thank you for the implementation! 
Albums from the shared library are displayed. It's ok. I have a few comments: 
- Cannot play videos in shared library albums 
- please add also automatically generated albums like people, places etc. to the "folder" of the shared library like in personal library 
- Browsing all the images from both libraries (separately) would also be great.
Thak you for this addon!

**Comment by Quark987** [comment]
I revisited the way shared library support is added. Either browsing the personal or shared library is now defined by a setting in the configurations window (where you enter your name and password). This way you now not only have the albums in the shared library, but also the people, places, etc. Video support should also be resolved.

I'll add support for all the photos on the timeline later, but you can already go ahead and give it a try, the latest version is on the master branch.

**Comment by Quark987** [comment]
As for the request to browse all the images from both libraries, how is this different from the menu 'recently added'? This chronologically lists all the photos.

**Comment by majnerp1** [comment]
Switching the library in the configuration is perfect. Albums, people, etc. work flawlessly. 

There are chronologically arranged photos in the "recently added" folder, but only about 1 month ago. Browse all photos = timeline, this would be a useful feature.

I have one more question about playing videos. All my tested videos in the library (the same in shared and personal) are stored in 1920x1080 resolution. Some play in full resolution and some in 1280x720. Is it possible to force playback to the selected (maximum) resolution?

**Comment by Quark987** [comment]
I can add an album with all photos, but I then need to create multiple pages where you can browse through, otherwise populating the list will take too long. I'll try to take care of this.

As for the videos, if you compare the playback resolution with what you get through moments in the browser, do you then have the same issue?

**Comment by majnerp1** [comment]
Through the web browser (chrome) videos are  played in full HD (original size) ok, and I can choose middle or original playback quality.

In Kodi addon - videos from own created personal album are played in original size Full HD. From "videos" or "recently added" the same videos are played only in HD resolution with poor framerate.
I don't know why. Is possible to force control playback quality of videos? The same issue on Kodi at Samsung S7 and Kodi on Chromacast Google TV (not testedon PC). My Synology model is DS118.

**Comment by Quark987** [comment]
I'm not sure it's possible to force the quality of the playback. I'll leave that as a feature request and close this issue.
