### ISSUE TITLE
Synology photos

### ISSUE THREAD

**Issue by robertoclg** [Quark987/plugin.video.moments#3]
Have you planned to make an addon for synology photos on dsm 7?

**Comment by Quark987** [comment]
I recently also moved to DSM 7 with Synology Photos, I'll try to create a new add on for this version.

**Comment by robertoclg** [comment]
> I recently also moved to DSM 7 with Synology Photos, I'll try to create a new add on for this version.

It's a fantastic notice if you need some tester tell to me. Thanks in advance and good job!

**Comment by Quark987** [comment]
I created a new github project for Synology Photos [here](https://github.com/Quark987/plugin.video.photos).
There is a problem with shared videos, I'll try to fix that later, the rest should be functional. If not, please let me know by filing an issue report on the github project page.
